<a href="https://colab.research.google.com/github/HarikrishnanK9/HarikrishnanK9/blob/main/lung_cancer_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/lung_cancer_examples.csv")
df

,Name,Surname,Age,Smokes,AreaQ,Alkhol,Result
0,John,Wick,35,3,5,4,1
1,John,Constantine,27,20,2,5,1
2,Camela,Anderson,30,0,5,2,0
3,Alex,Telles,28,0,8,1,0
4,Diego,Maradona,68,4,5,6,1
5,Cristiano,Ronaldo,34,0,10,0,0
6,Mihail,Tal,58,15,10,0,0
7,Kathy,Bates,22,12,5,2,0
8,Nicole,Kidman,45,2,6,0,0
9,Ray,Milland,52,18,4,5,1


In [2]:
df.isna().sum()

Name       0
Surname    0
Age        0
Smokes     0
AreaQ      0
Alkhol     0
Result     0
dtype: int64

In [3]:
df.duplicated().sum()

0

In [9]:
df1=df.drop(['Name','Surname'],axis=1)
df1

,Age,Smokes,AreaQ,Alkhol,Result
0,35,3,5,4,1
1,27,20,2,5,1
2,30,0,5,2,0
3,28,0,8,1,0
4,68,4,5,6,1
5,34,0,10,0,0
6,58,15,10,0,0
7,22,12,5,2,0
8,45,2,6,0,0
9,52,18,4,5,1


In [12]:
x=df1.iloc[:,:-1].values
x

array([[35,  3,  5,  4],
       [27, 20,  2,  5],
       [30,  0,  5,  2],
       [28,  0,  8,  1],
       [68,  4,  5,  6],
       [34,  0, 10,  0],
       [58, 15, 10,  0],
       [22, 12,  5,  2],
       [45,  2,  6,  0],
       [52, 18,  4,  5],
       [33,  4,  8,  0],
       [18, 10,  6,  3],
       [25,  2,  5,  1],
       [28, 20,  2,  8],
       [34, 25,  4,  8],
       [39, 18,  8,  1],
       [42, 22,  3,  5],
       [19, 12,  8,  0],
       [62,  5,  4,  3],
       [73, 10,  7,  6],
       [55, 15,  1,  3],
       [33,  8,  8,  1],
       [22, 20,  6,  2],
       [44,  5,  8,  1],
       [77,  3,  2,  6],
       [21, 20,  5,  3],
       [37, 15,  6,  2],
       [34, 12,  8,  0],
       [55, 20,  1,  4],
       [40, 20,  2,  7],
       [36, 13,  5,  2],
       [56, 20,  3,  3],
       [47, 15,  1,  8],
       [62, 25,  3,  4],
       [26, 10,  7,  2],
       [25, 20,  8,  2],
       [59, 20,  3,  4],
       [62, 15,  5,  5],
       [33, 25,  8,  2],
       [37, 10,  5,  3],


In [14]:
y=df1.iloc[:,-1].values
y

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [23]:
x_train
y_train

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [25]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.15393627e+00, -4.32694254e-01,  4.04969135e-01,
        -1.08797778e+00],
       [ 1.77961940e+00, -8.48486388e-01,  8.09938269e-01,
         1.16490550e+00],
       [-5.29775492e-01, -4.32694254e-01,  1.62471662e-17,
        -6.37401124e-01],
       [-1.55279023e-01, -5.71291632e-01,  4.04969135e-01,
        -6.37401124e-01],
       [-3.42527258e-01, -1.55499497e-01,  8.09938269e-01,
        -6.37401124e-01],
       [ 2.02928371e+00,  5.37487393e-01,  1.62471662e-17,
         2.63752189e-01],
       [-3.42527258e-01,  2.60292637e-01,  1.21490740e+00,
        -1.08797778e+00],
       [ 4.68881757e-01,  2.60292637e-01, -4.04969135e-01,
         7.14328846e-01],
       [-6.54607648e-01, -5.71291632e-01,  1.21490740e+00,
        -1.53855444e+00],
       [-4.67359414e-01, -1.55499497e-01,  4.04969135e-01,
        -6.37401124e-01],
       [-1.55279023e-01,  8.14682150e-01, -8.09938269e-01,
         7.14328846e-01],
       [ 2.02928371e+00, -1.81866804e+00, -1.21490740e+00,
      

In [26]:
x_test

array([[-5.92191570e-01, -1.81866804e+00,  1.62471662e-17,
         2.63752189e-01],
       [-6.54607648e-01, -2.23446017e+00,  2.02484567e+00,
        -1.53855444e+00],
       [-1.15393627e+00, -8.48486388e-01,  8.09938269e-01,
        -6.37401124e-01],
       [-1.02910412e+00,  5.37487393e-01, -1.21490740e+00,
         2.06605882e+00],
       [-1.46601666e+00,  5.37487393e-01,  1.21490740e+00,
        -1.86824467e-01],
       [-5.92191570e-01,  5.37487393e-01,  1.62471662e-17,
        -1.08797778e+00],
       [-9.28629454e-02,  1.92346117e+00, -8.09938269e-01,
         2.06605882e+00],
       [-1.46601666e+00,  5.37487393e-01,  1.62471662e-17,
        -1.86824467e-01],
       [-1.02910412e+00, -8.48486388e-01, -4.04969135e-01,
        -1.08797778e+00],
       [-1.21635235e+00, -1.95726541e+00,  1.62471662e-17,
        -1.08797778e+00],
       [ 1.09304254e+00,  5.37487393e-01,  1.62471662e-17,
         1.16490550e+00],
       [-1.02910412e+00, -2.23446017e+00,  1.21490740e+00,
      

In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [28]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [29]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])

In [34]:
print(knn.predict([[36,13,5,2]]))

[1]


In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)
print(score)

0.9444444444444444
